#!/usr/bin/env bash
# install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
# Adjust Firewall
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
# Restart Nginx
sudo service nginx start
