#!/usr/bin/env bash
# install Nginx
sudo apt-get  update
sudo apt-get install -y nginx
# Adjust Firewall
sudo ufw allow 'Nginx HTTP'
echo 'Hello World' > /var/www/html/index.html
# Restart Nginx
service nginx restart