#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    timeout client 5s
    timeout connect 5s
    timeout server 5s
    timeout http-request 5s

frontend my_frontend
    bind 0.0.0.0:80
    mode http
    default_backend web_backend

backend web_backend
    balance roundrobin
    server 501006-web-01 34.207.211.205 check
    server 501006-web-02 54.162.98.18 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
sudo restart haproxy