#!/usr/bin/env bash
# install the software-properties-common package
sudo apt install --no-install-recommends software-properties-common
# adds a Personal Package Archive (PPA) repository to the system
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
apt-get update
apt install haproxy
# Create config file
echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    daemon
    maxconn 2000
    log stdout format raw local0
    user haproxy

frontend http-in
    bind *:80
    mode http
    default_backend servers
backend web_servers
    balance roundrobin
    server 501006-web-01 34.207.211.205 check
    server 501006-web-02 54.162.98.18 check
    " >> /etc/haproxy/haproxy.cfg


sudo service haproxy restart