#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.

while read -r file;
do
    username=$(echo "$file" | cut -d ':' -f1)
    password=$(echo "$file" | cut -d ':' -f2)
    user_id=$(echo "$file" | cut -d ':' -f3)
    group_id=$(echo "$file" | cut -d ':' -f4)
    user_id_info=$(echo "$file" | cut -d ':' -f5)
    home=$(echo "$file" | cut -d ':' -f6)
    command=$(echo "$file" | cut -d ':' -f7)

    echo "The user $username is part of the $group_id gang, lives in $home and rides $command. $user_id's place is protected by the passcode $password, more info about the user here: $user_id_info"

done < "/etc/passwd"